<a href="https://colab.research.google.com/github/yoonju977/AI/blob/main/pytorch_%EC%8B%A4%EC%8A%B51.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118


In [2]:
pip install numpy

In [1]:
import time
import numpy as np
import torch

# 1. 일반 Python 리스트 연산 시간 측정
start_time = time.time()

X = [1] * 10000
Y = [0.5] * 10000
Z = [None] * 10000
for i in range(10000):
    Z[i] = X[i] * Y[i]

end_time = time.time()
print(f"Execution time for Python list operation: {end_time - start_time} seconds")

# 2. numpy 배열 연산 시간 측정
start_time = time.time()

X = np.full((10000,), 1)
Y = np.full((10000,), 0.5)
Z = X * Y

end_time = time.time()
print(f"Execution time for numpy operation: {end_time - start_time} seconds")

# 3. PyTorch 연산 시간 측정 (CUDA 사용)
start_time = time.time()

X = torch.full((10000,), 1.0, requires_grad=True).cuda()
Y = torch.full((10000,), 0.5, requires_grad=True).cuda()
Z = X * Y

# CUDA 연산 동기화 (GPU 작업 완료 후 시간 기록을 위해 필요)
torch.cuda.synchronize()

end_time = time.time()
print(f"Execution time for PyTorch CUDA operation: {end_time - start_time} seconds")

# 역전파 (backward) 계산
Z.sum().backward()

# 그라디언트 확인
dx = X.grad
print(dx)

Execution time for Python list operation: 0.004134178161621094 seconds
Execution time for numpy operation: 0.0007352828979492188 seconds
Execution time for PyTorch CUDA operation: 0.6567487716674805 seconds
None


<ipython-input-1-9f95dc340a80>:44: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  dx = X.grad


In [2]:
import torch
import numpy as np

# PyTorch tensor 생성 (기본적으로 torch.float32)
tensor_a = torch.tensor([5., 3.])
print(tensor_a)  # 출력: tensor([5., 3.]) - 기본 데이터 타입은 torch.float32

# NumPy 배열을 PyTorch tensor로 변환 (NumPy는 기본적으로 float64 사용)
numpy_array = np.array([5., 3.])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)  # 출력: tensor([5., 3.], dtype=torch.float64) - NumPy의 기본 dtype은 float64

# PyTorch tensor를 NumPy 배열로 변환 (기본적으로 float32 유지)
numpy_from_tensor = torch.tensor([5., 3.]).numpy()
print(numpy_from_tensor)  # 출력: array([5., 3.], dtype=float32) - PyTorch 기본 dtype은 float32


tensor([5., 3.])
tensor([5., 3.], dtype=torch.float64)
[5. 3.]


In [12]:
import torch
torch.ones(5, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
import torch
torch.randn(5, 3)

tensor([[-1.2213, -0.8613, -0.0631],
        [-2.4239,  0.3438,  0.1875],
        [-2.2954,  0.5382, -1.5464],
        [ 1.1598, -1.0788,  2.0342],
        [ 0.1197,  0.5335,  1.0518]])

In [13]:
import torch
tensor= torch.tensor([[ 0.2349, -0.0427, -0.5053], [ 0.6455,  0.1199, 0.4239]])
ones_tensor = torch.ones_like(tensor, dtype=torch.float64)

print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
import torch
torch.empty(5, 3) #공간만 할당했으므로 랜덤한 초기값

tensor([[4.6906e+17, 4.4131e-41, 2.8444e-11],
        [3.1742e-41, 2.6506e-11, 3.1742e-41],
        [2.5709e-11, 3.1742e-41, 0.0000e+00],
        [0.0000e+00, 2.4825e-11, 3.1742e-41],
        [1.8576e-13, 3.1742e-41, 8.6535e+15]])

In [16]:
import torch

print(torch.tensor([[5., 3.]])[0, :])  # 인덱싱 후 출력

print(torch.tensor([[5., 3.]]).view(-1))  # view(-1) 후 출력

print(torch.tensor([[5., 3.]]).view(2))  # view(2) 후 출력

print(torch.tensor([[5., 3.]]).size())  # 크기(size) 출력


tensor([5., 3.])
tensor([5., 3.])
tensor([5., 3.])
torch.Size([1, 2])


In [19]:
import torch

X = torch.ones((3, 3, 3))
Y = torch.ones((1, 1, 3))
Z = X * Y
Z.size()

torch.Size([3, 3, 3])

In [25]:
import torch

# CUDA가 사용 가능한지 확인
if torch.cuda.is_available():
    device = torch.device("cuda")  # CUDA 장치를 사용
    # GPU에서 텐서 생성
    x = torch.ones(2, device=device)
    # 다른 텐서를 CPU에서 생성하고 GPU로 이동
    y = torch.ones(2).to(device)

    # GPU에서 두 텐서의 합 계산
    z = x + y
    print(z)  # z는 GPU에 있는 텐서

    # z 텐서를 CPU로 이동하고, dtype을 double로 변환
    print(z.to("cpu", torch.double))
else:
    print("CUDA is not available.")

#	1.	x.cuda(): 텐서를 GPU로 이동시킬 때 사용합니다.(gpu 사용가능 환경만 가능)
# 2.	x.cpu(): 텐서를 CPU로 이동시킬 때 사용합니다.(어느 환경이던 가능)


tensor([2., 2.], device='cuda:0')
tensor([2., 2.], dtype=torch.float64)
